#ifndef RCC_H_
#define RCC_H_

#include <stdint.h>

struct rcc{
    volatile uint32_t CR;
    volatile uint32_t CFGR;
    volatile uint32_t CIR;
    volatile uint32_t APB2RSTR;
    volatile uint32_t APB1RSTR;
    volatile uint32_t AHBENR;
    volatile uint32_t APB2ENR;
    volatile uint32_t APB1ENR;
    volatile uint32_t BDCR;
    volatile uint32_t CSR;
    volatile uint32_t AHBRSTR;
    volatile uint32_t CFGR2;
    volatile uint32_t CFGR3;
};
#define RCC ((struct rcc*) 0x40021000)


/* CFGR3 */
#define RCC_CFGR3_USART1SW_PCLK     (0UL << 0)
#define RCC_CFGR3_USART1SW_SYSCLK   (1UL << 0)
#define RCC_CFGR3_USART1SW_LSE      (2UL << 0)
#define RCC_CFGR3_USART1SW_HSI      (3UL << 0)

#define RCC_CFGR3_USART2SW_PCLK     (0UL << 16)
#define RCC_CFGR3_USART2SW_SYSCLK   (1UL << 16)
#define RCC_CFGR3_USART2SW_LSE      (2UL << 16)
#define RCC_CFGR3_USART2SW_HSI      (3UL << 16)



/* AHBENR */
#define RCC_AHBENR_DMA1EN   (1UL << 0)
#define RCC_AHBENR_DMA2EN   (1UL << 1)
#define RCC_AHBENR_SRAMEN   (1UL << 2)
#define RCC_AHBENR_FLITFEN  (1UL << 4)
#define RCC_AHBENR_FMCEN    (1UL << 5)
#define RCC_AHBENR_CRCEN    (1UL << 6)
#define RCC_AHBENR_GPIOHEN  (1UL << 16)
#define RCC_AHBENR_GPIOAEN  (1UL << 17)
#define RCC_AHBENR_GPIOBEN  (1UL << 18)
#define RCC_AHBENR_GPIOCEN  (1UL << 19)
#define RCC_AHBENR_GPIODEN  (1UL << 20)
#define RCC_AHBENR_GPIOEEN  (1UL << 21)
#define RCC_AHBENR_GPIOFEN  (1UL << 22)
#define RCC_AHBENR_GPIOGEN  (1UL << 23)
#define RCC_AHBENR_TSCEN    (1UL << 24)
#define RCC_AHBENR_ADC12EN  (1UL << 28)
#define RCC_AHBENR_ADC34EN  (1UL << 29)


/* AHBRSTSR */
#define RCC_AHBRSTR_FMCRST    (1UL << 5)
#define RCC_AHBRSTR_GPIOHRST  (1UL << 16)
#define RCC_AHBRSTR_GPIOARST  (1UL << 17)
#define RCC_AHBRSTR_GPIOBRST  (1UL << 18)
#define RCC_AHBRSTR_GPIOCRST  (1UL << 19)
#define RCC_AHBRSTR_GPIODRST  (1UL << 20)
#define RCC_AHBRSTR_GPIOERST  (1UL << 21)
#define RCC_AHBRSTR_GPIOFRST  (1UL << 22)
#define RCC_AHBRSTR_GPIOGRST  (1UL << 23)
#define RCC_AHBRSTR_TSCRST    (1UL << 24)
#define RCC_AHBRSTR_ADC12RST  (1UL << 28)
#define RCC_AHBRSTR_ADC34RST  (1UL << 29)


/* Same bith positions in both */
/* APB1ENR, ABP1RSTR */
#define RCC_APB1_TIM2   (1UL << 0)
#define RCC_APB1_TIM3   (1UL << 1)
#define RCC_APB1_TIM4   (1UL << 2)
#define RCC_APB1_TIM6   (1UL << 4)
#define RCC_APB1_TIM7   (1UL << 5)
#define RCC_APB1_WWDG   (1UL << 11)
#define RCC_APB1_SPI2   (1UL << 14)
#define RCC_APB1_SPI3   (1UL << 15)
#define RCC_APB1_USART2 (1UL << 17)
#define RCC_APB1_USART3 (1UL << 18)
#define RCC_APB1_UART4  (1UL << 19)
#define RCC_APB1_UART5  (1UL << 20)
#define RCC_APB1_I2C1   (1UL << 21)
#define RCC_APB1_I2C2   (1UL << 22)
#define RCC_APB1_USB    (1UL << 23)
#define RCC_APB1_CAN    (1UL << 25)
#define RCC_APB1_DAC2   (1UL << 26)
#define RCC_APB1_PWR    (1UL << 28)
#define RCC_APB1_DAC1   (1UL << 29)
#define RCC_APB1_I2C3   (1UL << 30)

#define RCC_APB1ENR_TIM2EN    RCC_APB1_TIM2   
#define RCC_APB1ENR_TIM3EN    RCC_APB1_TIM3  
#define RCC_APB1ENR_TIM4EN    RCC_APB1_TIM4  
#define RCC_APB1ENR_TIM6EN    RCC_APB1_TIM6  
#define RCC_APB1ENR_TIM7EN    RCC_APB1_TIM7  
#define RCC_APB1ENR_WWDGEN    RCC_APB1_WWDG  
#define RCC_APB1ENR_SPI2EN    RCC_APB1_SPI2  
#define RCC_APB1ENR_SPI3EN    RCC_APB1_SPI3  
#define RCC_APB1ENR_USART2EN  RCC_APB1_USART2
#define RCC_APB1ENR_USART3EN  RCC_APB1_USART3
#define RCC_APB1ENR_UART4EN   RCC_APB1_UART4 
#define RCC_APB1ENR_UART5EN   RCC_APB1_UART5 
#define RCC_APB1ENR_I2C1EN    RCC_APB1_I2C1  
#define RCC_APB1ENR_I2C2EN    RCC_APB1_I2C2  
#define RCC_APB1ENR_USBEN     RCC_APB1_USB   
#define RCC_APB1ENR_CANEN     RCC_APB1_CAN   
#define RCC_APB1ENR_DAC2EN    RCC_APB1_DAC2  
#define RCC_APB1ENR_PWREN     RCC_APB1_PWR   
#define RCC_APB1ENR_DAC1EN    RCC_APB1_DAC1  
#define RCC_APB1ENR_I2C3EN    RCC_APB1_I2C3                  

#define RCC_APB1RSTR_TIM2RST    RCC_APB1_TIM2   
#define RCC_APB1RSTR_TIM3RST    RCC_APB1_TIM3  
#define RCC_APB1RSTR_TIM4RST    RCC_APB1_TIM4  
#define RCC_APB1RSTR_TIM6RST    RCC_APB1_TIM6  
#define RCC_APB1RSTR_TIM7RST    RCC_APB1_TIM7  
#define RCC_APB1RSTR_WWDGRST    RCC_APB1_WWDG  
#define RCC_APB1RSTR_SPI2RST    RCC_APB1_SPI2  
#define RCC_APB1RSTR_SPI3RST    RCC_APB1_SPI3  
#define RCC_APB1RSTR_USART2RST  RCC_APB1_USART2
#define RCC_APB1RSTR_USART3RST  RCC_APB1_USART3
#define RCC_APB1RSTR_UART4RST   RCC_APB1_UART4 
#define RCC_APB1RSTR_UART5RST   RCC_APB1_UART5 
#define RCC_APB1RSTR_I2C1RST    RCC_APB1_I2C1  
#define RCC_APB1RSTR_I2C2RST    RCC_APB1_I2C2  
#define RCC_APB1RSTR_USBRST     RCC_APB1_USB   
#define RCC_APB1RSTR_CANRST     RCC_APB1_CAN   
#define RCC_APB1RSTR_DAC2RST    RCC_APB1_DAC2  
#define RCC_APB1RSTR_PWRRST     RCC_APB1_PWR   
#define RCC_APB1RSTR_DAC1RST    RCC_APB1_DAC1  
#define RCC_APB1RSTR_I2C3RST    RCC_APB1_I2C3                  

/* APB2ENR, ABP2ST */
#define RCC_APB2_SYSCFG (1UL << 0)
#define RCC_APB2_TIM1   (1UL << 11)
#define RCC_APB2_SPI1   (1UL << 12)
#define RCC_APB2_TIM8   (1UL << 13)
#define RCC_APB2_USART1 (1UL << 14)
#define RCC_APB2_SPI4   (1UL << 15)
#define RCC_APB2_TIM15  (1UL << 16)
#define RCC_APB2_TIM16  (1UL << 17)
#define RCC_APB2_TIM17  (1UL << 18)
#define RCC_APB2_TIM20  (1UL << 20)

#define RCC_APB2ENR_SYSCFGEN    RCC_APB2_SYSCFG
#define RCC_APB2ENR_TIM1EN      RCC_APB2_TIM1  
#define RCC_APB2ENR_SPI1EN      RCC_APB2_SPI1  
#define RCC_APB2ENR_TIM8EN      RCC_APB2_TIM8  
#define RCC_APB2ENR_USART1EN    RCC_APB2_USART1
#define RCC_APB2ENR_SPI4EN      RCC_APB2_SPI4  
#define RCC_APB2ENR_TIM15EN     RCC_APB2_TIM15 
#define RCC_APB2ENR_TIM16EN     RCC_APB2_TIM16 
#define RCC_APB2ENR_TIM17EN     RCC_APB2_TIM17 
#define RCC_APB2ENR_TIM20EN     RCC_APB2_TIM20 

#define RCC_APB2RSTR_SYSCFGRST  RCC_APB2_SYSCFG
#define RCC_APB2RSTR_TIM1RST    RCC_APB2_TIM1  
#define RCC_APB2RSTR_SPI1RST    RCC_APB2_SPI1  
#define RCC_APB2RSTR_TIM8RST    RCC_APB2_TIM8  
#define RCC_APB2RSTR_USART1RST  RCC_APB2_USART1
#define RCC_APB2RSTR_SPI4RST    RCC_APB2_SPI4  
#define RCC_APB2RSTR_TIM15RST   RCC_APB2_TIM15 
#define RCC_APB2RSTR_TIM16RST   RCC_APB2_TIM16 
#define RCC_APB2RSTR_TIM17RST   RCC_APB2_TIM17 
#define RCC_APB2RSTR_TIM20RST   RCC_APB2_TIM20 

#endif /* RCC_H_ */ 
